from __future__ import annotations

from html import escape

from .models import AuditStatus, EvidenceStatus
from .store import GrantStore


def render_packet(grant_store: GrantStore) -> str:
    if grant_store.status != AuditStatus.VERIFIED or not grant_store.packet_ready:
        raise ValueError("Packet unavailable until deterministic verification passes")

    evidence_rows = "".join(
        f"<tr><td>{escape(item.id)}</td><td>{escape(item.filename)}</td>"
        f"<td>{escape(item.kind.replace('_', ' ').title())}</td>"
        f"<td>{escape(item.source_ref)}</td><td><code>{escape(item.sha256[:16])}…</code></td></tr>"
        for item in grant_store.evidence.values()
        if item.status == EvidenceStatus.INCLUDED
    )
    claim_rows = "".join(
        f"<tr><td>{escape(item.id)}</td><td>{escape(item.statement)}</td>"
        f"<td>{item.claimed_value:,.0f} {escape(item.unit)}</td>"
        f"<td>{escape(', '.join(item.evidence_ids))}</td><td><span class='pass'>VERIFIED</span></td></tr>"
        for item in grant_store.claims.values()
    )
    requirement_rows = "".join(
        f"<tr><td>{escape(item.id)}</td><td>{escape(item.description)}</td>"
        f"<td>{escape(item.source_ref)}</td><td><span class='pass'>COVERED</span></td></tr>"
        for item in grant_store.requirements
    )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Verified grant report evidence packet</title>
<style>
body{{font:15px/1.55 Inter,Arial,sans-serif;color:#17211d;max-width:1000px;margin:40px auto;padding:0 28px}}
h1{{font-size:32px;margin-bottom:4px}} h2{{margin-top:34px;border-bottom:1px solid #cbd8d0;padding-bottom:8px}}
.meta{{color:#52635a}} .seal{{margin:24px 0;padding:18px;border:2px solid #197a4a;background:#ecfff4;border-radius:10px}}
table{{border-collapse:collapse;width:100%;font-size:13px}} th,td{{padding:10px;border:1px solid #d9e1dc;text-align:left;vertical-align:top}}
th{{background:#f4f7f5}} .pass{{font-weight:800;color:#12643c}} code{{font-size:12px}} footer{{margin-top:40px;color:#617168}}
@media print{{body{{margin:0}}}}
</style></head><body>
<p class="meta">Proofline evidence packet · generated only after deterministic verification</p>
<h1>{escape(grant_store.award.program)}</h1>
<p><strong>Recipient:</strong> {escape(grant_store.award.recipient)}<br>
<strong>Award:</strong> ${grant_store.award.award_amount:,.2f}<br>
<strong>Reporting period:</strong> {grant_store.award.reporting_start.isoformat()} to {grant_store.award.reporting_end.isoformat()}<br>
<strong>Report due:</strong> {grant_store.award.report_due.isoformat()}</p>
<div class="seal"><strong>VERIFIED — 0 unsupported material claims</strong><br>
Hashes, reporting dates, arithmetic, duplicate evidence, and source coverage passed independent checks.
This packet is ready for authorized human review; it has not been submitted externally.</div>
<h2>Requirement coverage</h2><table><thead><tr><th>ID</th><th>Obligation</th><th>Source</th><th>Status</th></tr></thead><tbody>{requirement_rows}</tbody></table>
<h2>Verified claims</h2><table><thead><tr><th>ID</th><th>Claim</th><th>Value</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{claim_rows}</tbody></table>
<h2>Evidence manifest</h2><table><thead><tr><th>ID</th><th>File</th><th>Type</th><th>Provenance</th><th>SHA-256</th></tr></thead><tbody>{evidence_rows}</tbody></table>
<h2>Resolution record</h2><p>The authorized reviewer excluded duplicate evidence E-102, carried out-of-period invoice E-201 forward, and attached September attendance log E-303. Original records remain represented in the application audit trail.</p>
<footer>Generated by Proofline. Deterministic policy—not model prose—controls the VERIFIED status.</footer>
</body></html>"""
